- name: add nginx repo
  apt_repository: repo='ppa:nginx/stable'

- name: install nginx
  apt: pkg=nginx-extras state=installed update_cache=true

- name: disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
