- hosts: server
  sudo: true
  vars:
    - domain: "127.0.0.1"
    - download_url: "http://wordpress.org/latest.tar.gz"
    - wpdirectory: "/var/www"
    - db_name: "wordpress"
    - db_user: "wordpress"
    - db_password: "wordpress"
    - mysql_root_password: "dbpass"
  roles:
    - kit
    - nginx
    - mysql
    - php5
    - wordpress
#  handlers:
#    - name: restart nginx
#      service: name=nginx state=restarted
   
