- name: install mysql server
  apt: pkg={{ item }}
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

# name: change root pass
- mysql_user: name=root password={{mysql_root_password}}
  ignore_errors: yes
    
